/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mustafa Özgen (https://sketchfab.com/mustafaozgen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/3d-pbr-rusty-hc-sr04-ultrasonic-sensor-d1931de6d50540eca718665e1b49f9fe
title: 3D PBR Rusty HC-SR04 Ultrasonic Sensor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/ultrasonic.glb')
  console.log(nodes)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[129.5, 53.5, 0]}>
            <mesh geometry={nodes.Board_Board_0.geometry} material={materials.Board} />
          </group>
          <group position={[-24, -70, -11]}>
            <mesh geometry={nodes.PinsPlastic_PinsPlastic_0.geometry} material={materials.PinsPlastic} />
          </group>
          <mesh geometry={nodes.Crystal_Crystal_0.geometry} material={materials.Crystal} />
          <group position={[-48, -119.03, -10.5]}>
            <mesh geometry={nodes.Pins_Pins_0.geometry} material={materials.Pins} />
          </group>
          <group position={[82.5, 0, 83.58]}>
            <mesh geometry={nodes.Grids_Grids_0.geometry} material={materials.Grids} />
          </group>
          <group position={[82.5, 0, 9.74]}>
            <mesh geometry={nodes.Inside_Inside_0.geometry} material={materials.Inside} />
          </group>
          <group position={[82.5, 0, 49.55]}>
            <mesh geometry={nodes.Outside_Outside_0.geometry} material={materials.Outside} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ultrasonic.glb')
