/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/ultrasonic.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0}>
            <group position={[-71.46, 9.27, 288.15]} rotation={[Math.PI / 2, 0, 0]} scale={[0.98, 0.82, 0.98]}>
              <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
            </group>
            <group position={[129.99, 10.2, 288.15]} rotation={[Math.PI / 2, 0, 0]} scale={[0.98, 0.82, 0.98]}>
              <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
            </group>
            <group position={[26.21, 10.14, 236.3]} scale={[0.77, 1.03, 0.13]}>
              <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
            </group>
            <group position={[19.46, -94.66, 236.75]} scale={[1, 1, 2.62]}>
              <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
            </group>
            <group position={[-0.63, -94.66, 236.92]} scale={[1, 1, 2.58]}>
              <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
            </group>
            <group position={[39.64, -94.67, 237.28]} scale={[1, 1, 2.49]}>
              <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
            </group>
            <group position={[59.74, -96.31, 236.76]} scale={[1, 1, 2.58]}>
              <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ultrasonic.glb')
