/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  let { nodes, materials } = useGLTF('/models/arduino_uno.glb')

  materials.Metal.metalness = 0.9
  materials.material.emissiveIntensity = 0.1
  materials.material.opacity = 0.1

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-6, 5.13, 12.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Arduino_Blue2_FiberGlass_0.geometry} material={materials.FiberGlass} />
            <mesh geometry={nodes.Arduino_Blue2_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Arduino_Blue2_Back_0.geometry} material={materials.Back} />
            <mesh geometry={nodes.Arduino_Blue2_LED_0.geometry} material={materials.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/arduino_uno.glb')
