import Head from 'next/head'
import styles from '../styles/Model.module.scss'

import Arduino from "../components/Models/Arduino";
import Navigation from "../components/Reusables/Navigation"
import { Canvas } from '@react-three/fiber';
import { PerspectiveCamera, OrbitControls } from '@react-three/drei';


export default function Home() {
  return (
    <>
      <Head>
        <title>Arduino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <div className={styles.model}>
          <Canvas >
            <ambientLight intensity={1.2} />
            <pointLight intensity={1.5} position={[10, 10, 10]} />
            <PerspectiveCamera makeDefault position={[150, 150, 150]} />
            <Arduino />
            <OrbitControls />
          </Canvas >
        </div>
      </main>
    </>
  )
}
