import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import Navigation from "../components/Reusables/Navigation"
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Arduino PPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <div className={styles.list}>
          {/* {["Arduino", "Ultrasonic", "More Comming Soon..."].map((model, index) => { */}
          {/*   return ( */}
          {/*     <div className={styles.card} key={`${index}`}> */}
          {/*       {model} */}
          {/*     </div> */}
          {/*   ) */}
          {/* })} */}
          <Link href="/arduino" passHref>
            <div className={styles.card} >
              {"Arduino"}
            </div>
          </Link>
          <Link href="/ultrasonic_sensor" passHref>
            <div className={styles.card} >
              {"Ultrasonic Sensor"}
            </div>
          </Link>
          <Link href="/" passHref>
            <div className={styles.card} >
              {"More Comming Soon..."}
            </div>
          </Link>
        </div>
      </main>
    </>
  )
}
