import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import Navigation from "../components/Reusables/Navigation"


export default function Home() {
  return (
    <>
      <Head>
        <title>Arduino PPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <div className={styles.list}>
        </div>
      </main>
    </>
  )
}
